export const USER_SUBSCRIPTION_TRIGGERS = {
  USER_CHANGED_THEME: "USER_CHANGED_THEME"
};

export const TODO_SUBSCRIPTION_TRIGGERS = {
  TODO_CREATED: "TODO_CREATED",
  TODO_EDITED: "TODO_EDITED",
  TODO_DELETED: "TODO_DELETED",
  COMPLETED_TODOS_DELETED: "COMPLETED_TODOS_DELETED"
};
